// <auto-generated />
namespace Saned.Delco.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CascadeDeleteRequestsNotificationMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascadeDeleteRequestsNotificationMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201708071107012_Cascade-Delete-Requests-NotificationMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
